before_script:
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv global 3.6.0
  - which python
  - python -V

lint:
  script:
    - flake8 --exclude node_modules --max-line-length=120

test:
  script:
    - python manage.py test
