before_script:
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv global 3.6.0
  - which python
  - python -V
  - echo "Merge current branch into master for testing"
  - git merge origin/master --no-commit --no-ff

lint:
  script:
    - flake8

test:
  script:
    - python manage.py test
