before_script:
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv global 3.6.0
  - which python
  - python -V

test:
  script:
    - pylint --load-plugins pylint_django --errors-only verleihtool/ depot/ rental/
